ctrl+r cycle_values video-rotate "90" "180" "270" "0"

# Fine-tuned Zooming (Alt + / -)
Alt++ add video-zoom  0.05
Alt+- add video-zoom -0.05

# Fine-tuned Panning (Alt + Arrow Keys)
Alt+LEFT  add video-pan-x  0.01
Alt+RIGHT add video-pan-x -0.01
Alt+UP    add video-pan-y  0.01
Alt+DOWN  add video-pan-y -0.01
