[General]
Aur_Tool_Name=paru
Backend=alpm
Current_Tab_Index=3
Distro_RSS_Url=https://archlinux.org/feeds/news/
Instant_Search=false
LastCheckUpdatesTime=@DateTime(\0\0\0\x10\0\0\0\0\0\0%\x8dj\x3\x8d\xba\xe0\0)
PackageList_Ordered_Col=0
PackageList_Sort_Order=0
Package_Download_Size_Column_Width=120
Package_Icon_Column_Width=38
Package_Name_Column_Width=400
Package_Repository_Column_Width=150
Package_Version_Column_Width=260
Search_Method=0
Show_Groups_Panel=false
Splitter_Horizontal_State=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xc0\0\0\0\xf9\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
Transaction_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\xad\0\0\0%\0\0\x2\x96\0\0\x1\x8e\0\0\0\xad\0\0\0%\0\0\x2\x96\0\0\x1\x8e\0\0\0\0\0\0\0\0\a\x80\0\0\0\xad\0\0\0%\0\0\x2\x96\0\0\x1\x8e)
Use_Default_App_Icon=true
Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x3W\0\0\x2\x4\0\0\0\0\0\0\0\0\0\0\x3W\0\0\x2\x4\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3W\0\0\x2\x4)
