include=~/.config/foot/colorscheme/current-theme.ini

font=monospace:size=9
pad=10x10 center-when-maximized-and-fullscreen

selection-target=both
workers=12

[bell]
urgent=yes
visual=yes

[scrollback]
lines=10000
indicator-position=none

[colors-dark]
alpha-mode=default

[cursor]
blink=yes
blink-rate=750
beam-thickness=1.8

[csd]
border-width=0

[key-bindings]
pipe-scrollback=[sh -c "f=$(mktemp) && cat - > $f && foot -a foot_scrollback nvim -c 'set buftype=nofile' -c 'normal G' $f; rm $f"] Control+Shift+h

# vim: ft=dosini
