# Appearance
borderpx=0
gappih=0
gappiv=0
gappoh=0
gappov=0

# Background dim level when special workspace is active (0.0 to 1.0, default 0.5)
special_dim=0.5

# Inner and outer gaps for windows on the special workspace
special_gappih=30
special_gappiv=30
special_gappoh=30
special_gappov=30

# Rose Pine Moon
rootcolor=0x232136ff
bordercolor=0x44415Aff
dropcolor=0x3E8FB055
splitcolor=0xEA9A97ff
focuscolor=0xC4A7E7ff
urgentcolor=0xEB6F92ff
maximizescreencolor=0xF6C177ff
scratchpadcolor=0x9CCFD8ff
globalcolor=0x3E8FB0ff
overlaycolor=0x393552ff

cursor_size=24
cursor_theme=Kitty

