## maclean conf file ##

## Directories to be considered junk. Additional folders may be added.
## One path on each line. Please Use Caution. Targets will be deleted.

_mc_junk_dirs=(
	~/.adobe
	~/.macromedia
)
