return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	branch = "master",
	main = "nvim-treesitter.configs",
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"lua",
			"javascript",
			"typescript",
			"tsx",
			"html",
			"css",
			"json",
			"bash",
			"c",
			"csv",
			"dart",
			"diff",
			"dockerfile",
			"go",
			"http",
			"json5",
			"jsdoc",
			"luadoc",
			"markdown",
			"markdown_inline",
			"prisma",
			"python",
			"regex",
			"rust",
			"scss",
			"sql",
			"tmux",
			"toml",
			"typespec",
			"vimdoc",
			"yaml",
			"zig",
			"ziggy",
			"ziggy_schema",
		},
		highlight = { enable = true },
		auto_install = true,
		indent = { enable = true },
	},
}
