# -*- conf -*-

# For documentation on these options, see `man fnott.ini`

# Global values
# output=<undefined>#
# min-width=0
# max-width=0
# max-height=0
stacking-order=top-down
anchor=top-right
edge-margin-vertical=0
edge-margin-horizontal=5
notification-margin=10
icon-theme=hicolor
max-icon-size=32
selection-helper=fuzzel --dmenu
# selection-helper-uses-null-separator=no
# play-sound=aplay ${filename}

# Default values, may be overridden in 'urgency' specific sections
# layer=top
# background=141415ff

# border-color=252530ff
border-radius=0
border-size=1

padding-vertical=12
padding-horizontal=15

# dpi-aware=no

title-font=monospace:size=11:style=bold
# title-color=cdcdcdff
title-format=

summary-font=monospace:size=10:style=bold
summary-color=cdcdcdff
summary-format=<b>%s</b>

body-font=monospace:size=10
body-color=cdcdcdff
body-format=%b

progress-bar-height=4
progress-color=cdcdcdff
# progress-style=bar

# sound-file=
# icon=

# Timeout values are in seconds. 0 to disable
# max-timeout=0
# default-timeout=0
# idle-timeout=0

[low]
background=252530ff
border-color=878787ff
default-timeout=5

[normal]
background=252530ff
border-color=cdcdcdff
default-timeout=10

[critical]
background=252530ff
border-color=d8647eff
default-timeout=0
