return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter").setup({
			ensure_installed = {
				"bash",
				"c",
				"comment",
				"cpp",
				"css",
				"dart",
				"diff",
				"dockerfile",
				"go",
				"goctl",
				"gomod",
				"gosum",
				"groovy",
				"html",
				"http",
				"javascript",
				"json",
				"json5",
				"latex",
				"lua",
				"luadoc",
				"markdown",
				"markdown_inline",
				"prisma",
				"python",
				"query",
				"rasi",
				"regex",
				"requirements",
				"rust",
				"sql",
				"tmux",
				"toml",
				"tsx",
				"typescript",
				"typespec",
				"typst",
				"udev",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
				"zig",
			},
			sync_install = false,
			auto_install = true,
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = false,
			},
			indent = {
				enable = true,
				disable = { "python", "c" },
			},
		})
	end,
}
