# layout support: tile,scroller,monocle,grid,deck,center_tile,vertical_tile,vertical_grid,vertical_deck,dwindle,fair,vertical_fair
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller


# Window Rule for apps
windowrule=tags:7,istagsilent:1,ignore_maximize:1,monitor:HDMI-A-1,appid:vesktop
windowrule=tags:7,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,appid:hnpfjngllnobngcgfapefoaidbinmjnm
windowrule=tags:7,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,appid:ibblmnobmgdmpoeblocemifbpglakpoi
windowrule=tags:8,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,appid:cinhimbnkkaeohfgghhklpknlkffjgod
windowrule=tags:8,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,appid:agimnkijcaahngcdmfeangaknmldooml
windowrule=tags:8,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,appid:eikjhbkpemdappjfcmdeeeamdpkgabmk
windowrule=tags:8,istagsilent:1,isfakefullscreen:1,monitor:HDMI-A-1,appid:pjibgclleladliembfgfagdaldikeohf
windowrule=tags:8,istagsilent:1,ignore_maximize:1,monitor:HDMI-A-1,appid:*tuner
windowrule=tags:9,istagsilent:1,isfullscreen:1,scroller_proportion:1.0,force_tearing:1,appid:osu*
windowrule=tags:9,istagsilent:1,isfullscreen:1,scroller_proportion:1.0,force_tearing:1,appid:steam_app_default
windowrule=tags:9,istagsilent:1,isfullscreen:1,scroller_proportion:1.0,force_tearing:1,appid:Etterna
windowrule=tags:5,istagsilent:1,ignore_maximize:1,appid:anki
windowrule=tags:9,istagsilent:1,ignore_maximize:1,appid:Lutris
windowrule=tags:6,istagsilent:1,ignore_maximize:1,appid:winboat
windowrule=force_tiled_state:1,width:470,height:1055,scroller_proportion:0.2,appid:Emulator
windowrule=isfloating:1,title:termfilechooser
windowrule=width:960,height:810,isfloating:1,appid:lazygit_popup
windowrule=width:960,height:810,isfloating:1,appid:foot_scrollback
